version: "3"

services:
  app:
    build: .
    image: "caiohenriquecal/app:1.1"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASS=mysecretpassword
    hostname: docker_composer_node_db
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword