
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-treino-curso-elven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-treino-curso-elven
  template:
    metadata:
      labels:
        app: app-treino-curso-elven
    spec:
      containers:
      - name: app-treino-curso-elven-node-kubernets
        image: caiohenriquecal/app:1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres-db-lb.postgres.svc.cluster.local
        - name: DATABASE_NAME
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_PASS
          value: "mysecretpassword"